- name: create directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
  - /etc/opt/elasticsearch

- name: check linux kernel configuration
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: yes

- name: copy service specification
  template:
    src: docker-compose.yml
    dest: /etc/opt/elasticsearch/docker-compose.yml
  notify: restart elasticsearch

- name: start ElasticSearch
  docker_service:
    project_src: /etc/opt/elasticsearch
    state: present
    restarted: yes
